
env_args:
    env: 'TicTacToe'
    source: 'handyrl.environments.tictactoe'
    #env: 'Geister'
    #source: 'handyrl.environments.geister'


train_args:
    gamma: 0.8
    forward_steps: 16
    entropy_regularization: 1.0e-1
    entropy_regularization_decay: 0.1
    update_episodes: 2000
    batch_size: 128
    minimum_episodes: 20000
    maximum_episodes: 200000
    num_batchers: 2
    worker:
        num_gather: 2
        num_process: 6
    lambda: 0.7
    policy_target: 'TD' # 'UGPO' 'VTRACE' 'TD' 'MC'
    value_target: 'TD' # 'VTRACE' 'TD' 'MC'
    seed: 0
    restart_epoch: 0


entry_args:
    remote_host: ''
    num_gather: 2
    num_process: 6

