
env_args:
    env: 'TicTacToe'
    source: 'handyrl.environments.tictactoe'
    #env: 'Geister'
    #source: 'handyrl.environments.geister'


train_args:
    observation: False
    gamma: 0.8
    forward_steps: 16
    compress_steps: 4
    entropy_regularization: 1.0e-1
    entropy_regularization_decay: 0.1
    update_episodes: 200
    batch_size: 128
    minimum_episodes: 200
    maximum_episodes: 200000
    num_batchers: 2
    eval_rate: 0.1
    worker:
        num_gather: 2
        num_process: 6
    lambda: 0.7
    policy_target: 'TD' # 'UGPO' 'VTRACE' 'TD' 'MC'
    value_target: 'TD' # 'VTRACE' 'TD' 'MC'
    policy_decay: 0.9
    planning:
        root_noise_alpha: 0.15
        root_noise_coef: 0.25
    seed: 0
    restart_epoch: 0


entry_args:
    remote_host: ''
    num_gather: 2
    num_process: 6

