
env_args:
    env: 'TicTacToe'
    #env: 'Geister'
    #env: 'HungryGeese'
    #env: 'handyrl.envs.parallel_tictactoe'  # specify by path

train_args:
    turn_based_training: True
    observation: False
    gamma: 0.8
    forward_steps: 32
    compress_steps: 4
    learning_rate: 6.0e-9
    entropy_regularization: 1.0e-1
    entropy_regularization_decay: 0.1
    update_episodes: 2000
    batch_size: 128
    minimum_episodes: 2000
    maximum_episodes: 150000
    epochs: -1
    num_batchers: 2
    eval_rate: 0.1
    worker:
        num_parallel: 6
    lambda: 0.7
    policy_target: 'TD' # 'UPGO' 'VTRACE' 'TD' 'MC'
    value_target: 'TD' # 'VTRACE' 'TD' 'MC'
    seed: 0
    restart_epoch: 1

eval_args:
    model_path: 'models/latest.pth'
    opponent: 'models/1.pth'
    games: 400
    processes: 1


worker_args:
    server_address: ''
    num_parallel: 8

