
env_args:
    env: 'HungryGeese'
    source: 'handyrl.envs.kaggle.hungry_geese'

train_args:
    turn_based_training: False
    observation: False
    gamma: 0.8
    forward_steps: 32
    compress_steps: 4
    learning_rate: 6.0e-10
    entropy_regularization: 2.0e-3
    entropy_regularization_decay: 0.3
    update_episodes: 2000
    batch_size: 128
    minimum_episodes: 2000
    maximum_episodes: 150000
    epochs: 120
    num_batchers: 7
    eval_rate: 0.001
    worker:
        num_parallel: 6
    lambda: 0.7
    policy_target: 'TD' # 'UPGO' 'VTRACE' 'TD' 'MC'
    value_target: 'TD' # 'VTRACE' 'TD' 'MC'
    seed: 0
    restart_epoch: 1

eval_args:
    model_path: 'models/latest.pth'
    opponent: 'models/1.pth'
    games: 200
    processes: 1


worker_args:
    server_address: ''
    num_parallel: 8

