
name: test_env_merge

on:
  pull_request:
    types: closed
  branches:
    - 'master'

jobs:
  pytest:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Python 3.7
        if: github.event.pull_request.merged == true
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        if: github.event.pull_request.merged == true
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: pytest
        if: github.event.pull_request.merged == true
        run: |
          python -m pytest tests